version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: sql-adminer
    restart: always
    ports:
      - 8081:8080